#!/bin/bash

set -e

sudo apt install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo

export PREFIX="$(pwd)/build/compiler"
echo $PREFIX
mkdir -p $PREFIX
export TARGET=i686-elf
export PATH="$PREFIX/bin:$PATH"

BINUTILS_VER=binutils-2.39
BINUTILS_DIR=$(mktemp -d)
cd $BINUTILS_DIR
curl -O http://ftp.gnu.org/gnu/binutils/$BINUTILS_VER.tar.gz
tar xf $BINUTILS_VER.tar.gz
mkdir binutils-build
cd binutils-build
../$BINUTILS_VER/configure --target=$TARGET --enable-interwork --enable-multilib --disable-nls --disable-werror --prefix=$PREFIX 2>&1 | tee configure.log
make all install 2>&1 | tee make.log

GCC_VER=gcc-12.2.0
GCC_DIR=$(mktemp -d)
cd $GCC_DIR
curl -O https://ftp.gnu.org/gnu/gcc/$GCC_VER/$GCC_VER.tar.gz
tar xf $GCC_VER.tar.gz
mkdir gcc-build
cd gcc-build
../$GCC_VER/configure --target=$TARGET --prefix="$PREFIX" --disable-nls --disable-libssp --enable-languages=c,c++ --without-headers
make all-gcc 
make all-target-libgcc 
make install-gcc 
make install-target-libgcc 
